plugins: musicbrainz duplicates

chroma:
    auto: no
acoustid:
  apikey: bcPOEMhUUd

musicbrainz:
  host: musicbrainz.org
  https: no
  ratelimit: 1
  ratelimit_interval: 1.0
  extra_tags: [alias, barcode, catalognum, country, label, media, tracks, year]
  genres: no
  genres_tag: genre
  external_ids:
    discogs: no
    bandcamp: no
    spotify: no
    deezer: no
    beatport: no
    tidal: no
  data_source_mismatch_penalty: 0.3 # preferred
  search_limit: 5
  aliases_as_credits: no

badfiles:
    check_on_import: yes
    import_action_on_error: skip # ask skip abort continue
    import_action_on_warning: continue # ask skip abort continue
    commands:
        ogg: myoggchecker --opt1 --opt2
        flac: flac --test --warnings-as-errors --silent

smartplaylist:
    relative_to: ~/Music
    playlist_dir: ~/.mpd/playlists
    forward_slash: no
    playlists:
        - name: all.m3u
          query: ''
        - name: DreamTheater.m3u
          query: 'artist:Dream Theater'
